version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  composer:
    image: composer:2
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

      